VERSION = 'v1.9.2'
def get(prompt)
  yes?(prompt + ' (y/n) >')
end

gem 'hirb'
gem 'kaminari'

#HEROKU GEMS
gem 'puma'
gem 'rails_12factor'

#DEVISE
if get(set_color 'Would you like to use Devise and Figaro?',:magenta)
  gem 'figaro'
  gem 'devise'
  after_bundle do
    puts(set_color 'Installing Figaro', :blue, :bold )
    run('figaro install')

    puts(set_color 'Installing Devise', :blue, :bold )
    generate('devise:install')

    puts(set_color 'Installing Devise Views', :blue, :bold )
    generate('devise:views')
  end

  if get(set_color 'Would you like to use CanCanCan or Pundit?',:magenta)
    if yes?('Use CanCanCan?')
      gem 'cancancan', '~> 1.10'
    else
      gem 'pundit'
    end
  end
end


#PROCFILE
puts(set_color 'Creating Procfile', :blue, :bold )
file 'Procfile',<<-CODE
  web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
CODE

#FAKER
gem_group :test, :development do
  gem 'faker'
end

#BOURBON
if get(set_color 'Would you like some Bourbon?', :magenta)
    gem 'bourbon'
    gem 'neat'
    gem 'bitters'

    if get(set_color 'Would you like to use Simple Form?', :magenta)
      gem 'simple_form'
      generate('simple_form:install')
    end

    puts(set_color 'Creating application.scss', :blue, :bold)

    file 'app/assets/stylesheets/application.scss', <<-CODE
    @import 'bourbon';
    @import 'base/base';
    @import 'neat';
    CODE

    puts(set_color 'Removing old application.css', :blue, :bold)

    run('rm app/assets/stylesheets/application.css')

    puts(set_color 'Installing Bitters library', :blue, :bold )

    inside('app/assets/stylesheets') do
      run('bitters install')
    end

    puts(set_color 'Removing old _base.scss', :blue, :bold )

    run('rm app/assets/stylesheets/base/_base.scss')

    puts(set_color 'Creating _base.scss', :blue, :bold )

    file 'app/assets/stylesheets/base/_base.scss', <<-CODE
    @import "variables";
    @import "grid-settings";
    @import "buttons";
    @import "forms";
    @import "lists";
    @import "tables";
    @import "typography";
    CODE
  end
end

#BUNDLE INSTALL
after_bundle do
  if get(set_color 'Would you like to create a new git repo and add everything to it?', :magenta)
    git :init
    git add: '--all'
    git commit: "-a -m 'Initial Commit [Generated by TIY Rails Template (#{VERSION})]'"

    if get(set_color 'Would you like to push your git repo to github?', :magenta)
      run('hub create')
      git push: '-u origin master'
      if get(set_color 'Would you like to open your newly created repo on github?', :magenta)
        remote = `git remote -v`
        unless remote.empty?
          url_pieces = remote.scan(/github\.com:(.*)\.git/)
          url = "https://github.com/#{url_pieces.first.first}"
          run("open #{url}")
        end
      end
    end
  end


  puts(set_color 'Stopping Spring', :blue, :bold )
  run('spring stop')

  puts(set_color 'Installing Rspec', :blue, :bold )
  generate('rspec:install')

  puts(set_color'Injecting Simplecov', :blue, :bold )
  inject_into_file "spec/spec_helper.rb", after: "# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration\n" do
    <<-CODE
    require 'simplecov'
    SimpleCov.start
    CODE
  end

  puts(set_color'Running `rake db:test:prepare`',:blue,:bold)
  run('rake db:test:prepare')

#HEROKU
  if get(set_color 'Would you like to create a new Heroku repo?', :magenta )
      run('heroku create')

    if get(set_color 'Would you like to push your repo to Heroku', :magenta )
        git push: 'heroku master'
        run('heroku run rake db:migrate')
    end

  end


  rake('db:create') if get(set_color 'Would you like to create your db with `rake db:create`', :magenta)
  yes?(set_color 'Remember to declare your ruby version in your gem file.', :red,  :bold)
  yes?(set_color 'If using cancancan, you need to run the `rails g cancan:ability`command.', :red, :bold)
  yes?(set_color 'If using pundit, you need to put `include Pundit` in your ApplicationController.',:red, :bold)
  yes?(set_color 'You need to run the command `figaro heroku:set -e production`, when using heroku.', :red, :bold)
  yes?(set_color 'The devise gem is installed, but you still need to run `rails generate devise MODEL.', :red, :bold)
  yes?(set_color 'I installed most of paperclip, you still need to add `has_attached_file` to your model', :red, :bold)
  yes?(set_color 'Complete! Your new rails app is finished and ready to go!', :red, :bold)
end

