#Rails TIY template

#Add heroku procfile
file('Procfile',  "web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}")

#Add ruby version to gemfile
ruby_version = ask("What is your ruby version? ")
insert_into_file "Gemfile", "ruby '#{ruby_version}'", :after => "source 'https://rubygems.org'\n"

#Add pg and puma gem
  gem 'pg'
  gem 'puma'

  gem_group :production do
    gem 'rails_12factor'
  end

  gem_group :development, :test do
    gem 'pry' if yes?("Do you want to use Pry? ")
    gem 'faker'
  end

  run "rm README.rdoc"
  run "touch README.md"

  if yes?("Do you want some Bourbon, Neat & Bitters? ")
      gem 'bourbon'
      gem 'neat'
      gem 'bitters'

      puts(set_color 'Creating application.scss', :blue, :bold)

      file 'app/assets/stylesheets/application.scss', <<-CODE
      @import 'bourbon';
      @import 'base/base';
      @import 'neat';
      CODE

      puts(set_color 'Removing old application.css', :blue, :bold)

      run('rm app/assets/stylesheets/application.css')

      puts(set_color 'Installing Bitters library', :blue, :bold )

      inside('app/assets/stylesheets') do
        run('bitters install')
      end

      puts(set_color 'Removing old _base.scss', :blue, :bold )

      run('rm app/assets/stylesheets/base/_base.scss')

      puts(set_color 'Creating _base.scss', :blue, :bold )

      file 'app/assets/stylesheets/base/_base.scss', <<-CODE
      @import "variables";
      @import "grid-settings";
      @import "buttons";
      @import "forms";
      @import "lists";
      @import "tables";
      @import "typography";
      CODE
    end

  if yes?("Do you want to use React? ")
    gem 'react-rails'
    run 'rails g react:install'
  end

  if yes?("Do you want to use bcrypt? ")
    gem 'bcrypt'
  end

  #BUNDLE INSTALL
  after_bundle do
    if get(set_color 'Would you like to create a new git repo and add everything to it?', :magenta)
      git :init
      git add: '--all'
      git commit: "-a -m 'Initial Commit [Generated by TIY Rails Template (#{VERSION})]'"

      if get(set_color 'Would you like to push your git repo to github?', :magenta)
        run('hub create')
        git push: '-u origin master'
        if get(set_color 'Would you like to open your newly created repo on github?', :magenta)
          remote = `git remote -v`
          unless remote.empty?
            url_pieces = remote.scan(/github\.com:(.*)\.git/)
            url = "https://github.com/#{url_pieces.first.first}"
            run("open #{url}")
          end
        end
      end
    end
  end


if get(set_color 'Would you like to create your db with `rake db:create`', :magenta)
  yes?(set_color 'Remember to declare your ruby version in your gem file.', :red,  :bold)
  yes?(set_color 'If using cancancan, you need to run the `rails g cancan:ability`command.', :red, :bold)
  yes?(set_color 'If using pundit, you need to put `include Pundit` in your ApplicationController.',:red, :bold)
  yes?(set_color 'You need to run the command `figaro heroku:set -e production`, when using heroku.', :red, :bold)
  yes?(set_color 'The devise gem is installed, but you still need to run `rails generate devise MODEL.', :red, :bold)
  yes?(set_color 'I installed most of paperclip, you still need to add `has_attached_file` to your model', :red, :bold)
  yes?(set_color 'Complete! Your new rails app is finished and ready to go!', :red, :bold)
end
